server {
    listen 80;
    listen [::]:80;
    server_name mortals.online www.mortals.online superego.mineaibd.com 8.152.201.187;

    access_log /var/log/nginx/superego.access.log;
    error_log /var/log/nginx/superego.error.log warn;
    client_max_body_size 64k;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    location / {
        return 308 https://mortals.online$request_uri;
    }
}
