import type { CultivationArt, Realm } from './types'

export const REALMS: Realm[] = [
  { name: '炼气', subtitle: '命火初燃', threshold: 0, accent: '#65e6ff' },
  { name: '筑基', subtitle: '本命愿成', threshold: 140, accent: '#8c8cff' },
  { name: '金丹', subtitle: '万法凝核', threshold: 360, accent: '#ffc86b' },
  { name: '元婴', subtitle: '超我显形', threshold: 680, accent: '#ff7edb' },
  { name: '化神', subtitle: '神通投世', threshold: 1100, accent: '#70ffbc' },
  { name: '返虚', subtitle: '愿业相化', threshold: 1650, accent: '#d9c9ff' },
  { name: '合道', subtitle: '超我归身', threshold: 2400, accent: '#fff4b5' },
  { name: '渡劫', subtitle: '十八关照命', threshold: 3300, accent: '#e7a665' },
  { name: '大乘', subtitle: '自救而不自弃', threshold: 4500, accent: '#fff0c9' },
]

export const DAILY_QUESTS = [
  { id: 'learn', icon: '经', title: '读一段经文', detail: '读懂一句人话，再投入灵炉', reward: '修为 +28', minutes: 3 },
  { id: 'act', icon: '行', title: '完成一个现实动作', detail: '照着场景指引，只做一个小动作', reward: '能力 +10', minutes: 5 },
  { id: 'observe', icon: '悟', title: '做一道情境选择', detail: '在故事里选一次，再听超我讲明白', reward: '愿力 +12', minutes: 2 },
]

export const PRACTICE_GESTURES = {
  heart: {
    name: '抚心',
    mark: '心',
    instruction: '把右手轻放在心口，慢慢呼吸三次。只感受，不评价。',
    meaning: '先和此刻的自己站在一起。',
  },
  release: {
    name: '松拳',
    mark: '松',
    instruction: '轻轻握拳，再慢慢松开，重复三次。',
    meaning: '提醒身体：我可以不立刻被情绪推着走。',
  },
  step: {
    name: '前行',
    mark: '行',
    instruction: '站起来，向前迈一步，再回到原位。',
    meaning: '用身体记住：再小的一步，也是开始。',
  },
}

export const SCRIPTURE_PRACTICES = [
  {
    id: 'water',
    scene: '雨落青石 · 若水关',
    source: '《道德经》',
    title: '不必每次都硬扛',
    original: '上善若水，水善利万物而不争。',
    plain: '真正有力量的人，不是什么都硬碰。能绕、能停、能借力，也是在往前。',
    question: '今天哪件事，你可以换一种更省力的做法？',
    art: '若水转圜诀',
    gesture: 'release' as const,
  },
  {
    id: 'practice',
    scene: '晨钟初响 · 温故台',
    source: '《论语》',
    title: '知道以后，要再做一次',
    original: '学而时习之，不亦说乎？',
    plain: '学会不是看懂那一下，而是隔一段时间再做一次，直到它真的变成你的。',
    question: '你愿意把哪一个小动作再练一次？',
    art: '温故成行诀',
    gesture: 'step' as const,
  },
  {
    id: 'no-attachment',
    scene: '空山镜湖 · 无住境',
    source: '《金刚经》',
    title: '别把一个念头当成全部的你',
    original: '应无所住，而生其心。',
    plain: '念头来了可以看见，但不必住进去。你仍然可以在当下重新选择。',
    question: '此刻哪个念头最容易把你困住？',
    art: '无住观心诀',
    gesture: 'heart' as const,
  },
]

export const ACTION_PRACTICES = [
  {
    id: 'two-minutes',
    scene: '案前灯影 · 万事难始',
    title: '只开始两分钟',
    situation: '任务堆在眼前，你越想一次做好，越不愿打开它。',
    dialogue: '超我：今天不许你做完。只打开那个页面，写下第一行，两分钟就停。',
    action: '打开你最想拖延的任务，只做第一个看得见的动作。',
    proof: '页面已打开，第一步已完成',
    gesture: 'step' as const,
  },
  {
    id: 'name-feeling',
    scene: '镜门回声 · 心浪将起',
    title: '先说清自己怎么了',
    situation: '消息弹出来，你的身体先紧了，脑中已经开始预演最坏结果。',
    dialogue: '超我：先别回。用一句话告诉我——“我现在有点……”。',
    action: '放下手机三次呼吸，说出一个准确感受，再决定要不要回复。',
    proof: '我已经说出此刻的感受',
    gesture: 'heart' as const,
  },
  {
    id: 'ask-help',
    scene: '负岳荒原 · 同行驿',
    title: '把求助说具体',
    situation: '你已经很累，却仍觉得开口会显得自己不够强。',
    dialogue: '超我：不要说“帮帮我”。只告诉一个可信的人，你具体需要哪一步帮助。',
    action: '给一个可信的人发一句具体请求：你能否在____上帮我____？',
    proof: '我已经发出一个具体请求',
    gesture: 'release' as const,
  },
]

export const WISDOM_PRACTICES = [
  {
    id: 'emotion-choice',
    scene: '心浪幻境 · 消息来时',
    title: '情绪来了，谁来掌舵？',
    situation: '一句刺耳的话让你瞬间生气。你最想立刻回击。',
    prompt: '哪一个选择更接近“先看见，再决定”？',
    choices: [
      { id: 'fight', label: '马上回击，不能让自己吃亏', correct: false, feedback: '这会让情绪替你做决定。保护自己没有错，但可以等身体先稳下来。' },
      { id: 'suppress', label: '假装没事，把情绪压下去', correct: false, feedback: '压住不等于看见。被忽略的情绪通常会换一种方式回来。' },
      { id: 'pause', label: '先停三次呼吸，说清感受再回复', correct: true, feedback: '对。觉察不是忍气吞声，而是把选择权从情绪手里拿回来。' },
    ],
    principle: '情绪是信号，不是命令。',
    gesture: 'heart' as const,
  },
  {
    id: 'perfect-choice',
    scene: '完美心魔 · 开工之前',
    title: '怎样才算真正开始？',
    situation: '你想把方案一次做漂亮，结果迟迟没有动手。',
    prompt: '此刻最有用的选择是什么？',
    choices: [
      { id: 'plan', label: '再找一些资料，等更有把握', correct: false, feedback: '资料可能有用，但此刻继续收集，更像是在躲开第一次不完美。' },
      { id: 'tiny', label: '先做一个能被看见的粗糙版本', correct: true, feedback: '对。行动会产生反馈，反馈才会让下一步更准确。' },
      { id: 'wait', label: '等状态好一点再开始', correct: false, feedback: '状态经常在开始以后才出现，不必等它先来。' },
    ],
    principle: '不用做好，先做出来。',
    gesture: 'step' as const,
  },
  {
    id: 'ideal-choice',
    scene: '无相天阶 · 理想凝视',
    title: '理想的自己该做什么？',
    situation: '你看着理想目标，越看越觉得现在的自己不配。',
    prompt: '哪种关系更能让人长期成长？',
    choices: [
      { id: 'judge', label: '让理想自我不断批评现在的我', correct: false, feedback: '羞耻能短暂推动，却很难支撑长期改变。理想不该成为鞭子。' },
      { id: 'forget', label: '干脆不要理想，就不会痛苦', correct: false, feedback: '放弃方向会减少一时压力，也会让愿力失去落点。' },
      { id: 'coach', label: '让理想自我成为教练，每次只拉一步', correct: true, feedback: '对。理想负责指路和陪伴，不负责审判此刻的你。' },
    ],
    principle: '愿力指路，不用理想惩罚自己。',
    gesture: 'release' as const,
  },
]

export const STORY_CHAPTERS = [
  {
    index: 0,
    code: '第一劫 01',
    title: '第一劫：镜门来客',
    scene: '识海废墟',
    requirement: 0,
    enemy: '无明与自弃',
    narrative: '识海被旧念淹没，命火只剩最后一线。就在你准备再次丢下自己时，镜门从黑暗里裂开。一个更强大的你从未来归来：你渡不过的劫，我先替你走；你读不完的经，我先替你参。',
    choice: '与未来的我缔结本命契',
    choices: [
      { id: 'trust', label: '先相信他一次', note: '不必现在变强，只把第一步交给未来的你。', effect: { will: 10, karma: -4, ability: 1 } },
      { id: 'question', label: '先问清他为何回来', note: '保持怀疑，但愿意听完他的答案。', effect: { will: 6, karma: -6, ability: 3 } },
    ],
    reward: '本命神通「照心」',
  },
  {
    index: 1,
    code: '第二劫 02',
    title: '第二劫：万事难始',
    scene: '拖延域',
    requirement: 80,
    enemy: '完美心魔',
    narrative: '此劫不以刀兵伤人，只让每一步都显得太大。超我在彼岸迎战完美心魔，把宏大的恐惧斩成一个两分钟就能完成的动作，再隔着镜门投给你。',
    choice: '接住「微行」投影',
    choices: [
      { id: 'tiny', label: '把第一步砍到两分钟', note: '先做出一个看得见的动作，不管它漂不漂亮。', effect: { will: 7, karma: -8, ability: 5 } },
      { id: 'witness', label: '请超我在旁边看着', note: '不再独自硬撑，让陪伴替你守住开始。', effect: { will: 10, karma: -5, ability: 3 } },
    ],
    reward: '玄品神通「微行破界」',
  },
  {
    index: 2,
    code: '第三劫 03',
    title: '第三劫：万卷困城',
    scene: '万卷城',
    requirement: 180,
    enemy: '知而不行',
    narrative: '万卷经书化成一座没有出口的城。这里考的不是记住多少，而是能否炼出一门真正救命的法。超我吞纳一卷、参悟一道、只留一术，把知识炼成能够投射现实的神通。',
    choice: '开启万法灵炉',
    choices: [
      { id: 'one-law', label: '只炼一条能用的法', note: '合上其余经卷，今天只让一条道理落地。', effect: { will: 5, karma: -7, ability: 6 } },
      { id: 'burn-notes', label: '烧掉无用的收藏', note: '承认“拥有”不等于“学会”，给真正重要的内容让路。', effect: { will: 8, karma: -9, ability: 3 } },
    ],
    reward: '地品神通「万法归身」',
  },
  {
    index: 3,
    code: '第四劫 04',
    title: '第四劫：镜中自缚',
    requirement: 320,
    scene: '自我镜门',
    enemy: '自我判决',
    narrative: '镜中每一道裂纹，都在重复“我就是不行”。超我没有替你砸碎镜子，而是从镜中伸出手：那不是事实，只是旧业留下的回声。把“我就是”改成“我此刻正在经历”，你便有了选择。',
    choice: '握住镜中伸来的手',
    choices: [
      { id: 'rename', label: '把“我就是”改成“我此刻”', note: '旧业是经历，不是你的名字。', effect: { will: 8, karma: -10, ability: 4 } },
      { id: 'evidence', label: '找一件反证旧判决的事', note: '不用喊口号，用一个真实证据松开锁链。', effect: { will: 5, karma: -7, ability: 7 } },
    ],
    reward: '天品神通「破妄归心」',
  },
  {
    index: 4,
    code: '第五劫 05',
    title: '第五劫：孤身负岳',
    requirement: 500,
    scene: '负岳荒原',
    enemy: '凡事独扛',
    narrative: '你把所有重量都背在自己身上，久而久之，连求助都像一种失败。超我在荒原上卸下一座山：借力不是退缩，是让愿力走得更远。真正的强大，不以孤独为代价。',
    choice: '允许自己借一次力',
    choices: [
      { id: 'ask', label: '向一个可信的人开口', note: '说清你具体需要哪一种帮助。', effect: { will: 7, karma: -8, ability: 6 } },
      { id: 'together', label: '召一位同道并肩', note: '让共同前进取代一个人扛到底。', effect: { will: 10, karma: -6, ability: 4 } },
    ],
    reward: '羁绊神通「同道借力」',
  },
  {
    index: 5,
    code: '第六劫 06',
    title: '第六劫：理想噬身',
    requirement: 700,
    scene: '无相天阶',
    enemy: '用理想的自己惩罚现在的自己',
    narrative: '理想自我高悬天阶，越是仰望，越觉得此刻的自己不配。超我转身走下神坛：我不是来审判你的，我是来拉你上去的。愿力可以指路，却不能成为鞭子。',
    choice: '让理想自我走下神坛',
    choices: [
      { id: 'embrace', label: '让他先抱住现在的我', note: '理想不再负责审判，只负责拉你一把。', effect: { will: 12, karma: -8, ability: 3 } },
      { id: 'enough', label: '允许今天做到七成', note: '给明天留一点余地，也给此刻留一点人味。', effect: { will: 7, karma: -10, ability: 6 } },
    ],
    reward: '化神之法「愿心不弃」',
  },
  {
    index: 6,
    code: '第七劫 07',
    title: '第七劫：昼夜倒悬',
    scene: '长夜城',
    requirement: 920,
    enemy: '靠透支换取短暂安心',
    narrative: '长夜城里没有日出，只有不断亮起的消息和永远做不完的事。超我熄灭一盏盏无用的灯：休息不是退场，而是在守住明日还能继续前行的命火。',
    choice: '替明日留下一盏命火',
    choices: [
      { id: 'close', label: '给今晚设置一个收尾时刻', note: '让今天有结束，明天才有真正的开始。', effect: { will: 9, karma: -9, ability: 5 } },
      { id: 'restore', label: '先补回一段真实休息', note: '不拿休息奖惩自己，把它当作长期战力。', effect: { will: 7, karma: -11, ability: 5 } },
    ],
    reward: '玄品神通「守夜归息」',
  },
  {
    index: 7,
    code: '第八劫 08',
    title: '第八劫：众声迷城',
    scene: '千面市',
    requirement: 1160,
    enemy: '把别人的期待当成自己的命令',
    narrative: '千面市里，每个人都在替你定义什么才算成功。超我没有堵住所有声音，只把你的本命愿重新挂到城门：意见可以听，路仍由你选。',
    choice: '从众声里认回自己的声音',
    choices: [
      { id: 'filter', label: '只留下有证据的意见', note: '把评价拆成事实、猜测和对方的偏好。', effect: { will: 10, karma: -7, ability: 5 } },
      { id: 'vow', label: '回到我的本命愿', note: '先问这条路是否更接近“我想成为谁”。', effect: { will: 12, karma: -6, ability: 3 } },
    ],
    reward: '地品神通「听见本心」',
  },
  {
    index: 8,
    code: '第九劫 09',
    title: '第九劫：欲念回环',
    scene: '即时乐土',
    requirement: 1420,
    enemy: '用短暂刺激逃开真实需要',
    narrative: '乐土每一次闪光都能让人忘掉五分钟的空洞，却把真正重要的事推得更远。超我把诱惑变成一道可见的浪：你不必消灭欲望，只要在浪来时多等十息。',
    choice: '在冲动和行动之间留一道缝',
    choices: [
      { id: 'delay', label: '先等十次呼吸', note: '冲动会起伏，十息后再决定是否照做。', effect: { will: 9, karma: -10, ability: 5 } },
      { id: 'need', label: '问清我真正缺什么', note: '把“想刷、想买、想逃”翻译成真实需要。', effect: { will: 8, karma: -8, ability: 7 } },
    ],
    reward: '地品神通「十息定浪」',
  },
  {
    index: 9,
    code: '第十劫 10',
    title: '第十劫：旧伤回潮',
    scene: '回声海',
    requirement: 1700,
    enemy: '把过去的危险当成此刻仍在发生',
    narrative: '回声海把旧日疼痛一遍遍送回岸边。超我没有命令海水退去，只在你脚下立起一块界碑：那件事发生过，但此刻的你已经多了选择、距离和援手。',
    choice: '区分过去与现在',
    choices: [
      { id: 'ground', label: '说出眼前五件真实事物', note: '先让身体确认：我在这里，此刻是安全的。', effect: { will: 8, karma: -10, ability: 6 } },
      { id: 'support', label: '把这一浪告诉可信的人', note: '不独自解释所有痛，让陪伴进入现场。', effect: { will: 10, karma: -8, ability: 5 } },
    ],
    reward: '天品神通「此岸定身」',
  },
  {
    index: 10,
    code: '第十一劫 11',
    title: '第十一劫：关系结界',
    scene: '无门庭',
    requirement: 2000,
    enemy: '用委屈自己维持所有关系',
    narrative: '无门庭里没有墙，任何人的要求都能直接闯进来。超我递给你一扇门：边界不是赶走别人，而是让关系知道怎样才能长久地相处。',
    choice: '立下一道温和而清楚的边界',
    choices: [
      { id: 'clear', label: '说清我能做和不能做的部分', note: '不控诉，也不含糊，让对方知道真实范围。', effect: { will: 10, karma: -8, ability: 7 } },
      { id: 'pause', label: '先不立刻答应', note: '用“我想一下再回复”替自己留出选择。', effect: { will: 8, karma: -9, ability: 6 } },
    ],
    reward: '天品神通「有门有我」',
  },
  {
    index: 11,
    code: '第十二劫 12',
    title: '第十二劫：完美天罚',
    scene: '无瑕天宫',
    requirement: 2320,
    enemy: '只有满分才配开始',
    narrative: '无瑕天宫会烧掉所有粗糙的第一稿，于是这里从未诞生任何真正的作品。超我故意留下一道不完美的刻痕：完成会带来反馈，反馈才会长出更好的下一版。',
    choice: '交出一个能被看见的第一版',
    choices: [
      { id: 'draft', label: '先做七成版本', note: '把可修改的东西交到现实，而不是只在脑中完美。', effect: { will: 8, karma: -10, ability: 8 } },
      { id: 'deadline', label: '给犹豫设一个截止点', note: '时间到了就提交，让结果替想象说话。', effect: { will: 9, karma: -8, ability: 7 } },
    ],
    reward: '天品神通「缺月成章」',
  },
  {
    index: 12,
    code: '第十三劫 13',
    title: '第十三劫：比较天河',
    scene: '万影长桥',
    requirement: 2660,
    enemy: '拿别人的高光审判自己的全程',
    narrative: '桥上悬着无数人的高光时刻，你却看不见他们的代价与漫长准备。超我把镜面转回脚下：你真正需要超过的，是昨日那条让自己反复受困的旧路。',
    choice: '把比较变成可用的坐标',
    choices: [
      { id: 'learn', label: '只提取一个可学动作', note: '不评价整个人生，只借走一个具体方法。', effect: { will: 8, karma: -7, ability: 8 } },
      { id: 'self', label: '和七天前的自己比较', note: '用自己的连续变化，替代无边界的横向审判。', effect: { will: 11, karma: -8, ability: 5 } },
    ],
    reward: '地品神通「照己量行」',
  },
  {
    index: 13,
    code: '第十四劫 14',
    title: '第十四劫：失控荒原',
    scene: '无图之地',
    requirement: 3020,
    enemy: '必须确定一切才敢前进',
    narrative: '荒原没有完整地图，每走一步地形才显现一寸。超我把“正确答案”换成一次小型试探：不确定不是停下的理由，而是缩小赌注、获取信息的理由。',
    choice: '用一次小试探换取真实信息',
    choices: [
      { id: 'experiment', label: '做一个七天小实验', note: '先验证方向，不急着宣布终身决定。', effect: { will: 8, karma: -8, ability: 9 } },
      { id: 'control', label: '只列出今天能控制的三件事', note: '把力气从未知处收回到手边。', effect: { will: 10, karma: -9, ability: 6 } },
    ],
    reward: '天品神通「无图试路」',
  },
  {
    index: 14,
    code: '第十五劫 15',
    title: '第十五劫：意义沉渊',
    scene: '无星深谷',
    requirement: 3400,
    enemy: '因为看不见终点，就否定今天',
    narrative: '深谷吞掉宏大的答案，只留下脚边一点微光。超我没有替你发明人生意义：意义往往不是想出来的，而是在照顾一个人、完成一件事、守住一次选择时被做出来的。',
    choice: '先做一件值得的事',
    choices: [
      { id: 'care', label: '照顾一个具体的人或自己', note: '让价值先发生，再等待意义慢慢显形。', effect: { will: 11, karma: -7, ability: 6 } },
      { id: 'craft', label: '把一件小事认真做完', note: '在完成中重建“我仍能影响世界”的证据。', effect: { will: 8, karma: -8, ability: 9 } },
    ],
    reward: '化神之法「微光有用」',
  },
  {
    index: 15,
    code: '第十六劫 16',
    title: '第十六劫：愿业倒转',
    scene: '因果轮台',
    requirement: 3800,
    enemy: '嘴上想改变，身体仍沿旧路自动前行',
    narrative: '因果轮台不会听口号，只会放大重复发生的动作。超我把愿力写成环境、时间和触发器：愿望若没有落在系统里，迟早会被旧习惯带走。',
    choice: '把愿力装进每天会发生的机关',
    choices: [
      { id: 'trigger', label: '为新习惯绑定一个旧动作', note: '在已经会发生的事之后，接上一个最小行动。', effect: { will: 8, karma: -10, ability: 9 } },
      { id: 'friction', label: '给旧路增加一点阻力', note: '把诱因移远，让更好的选择更容易发生。', effect: { will: 9, karma: -11, ability: 7 } },
    ],
    reward: '返虚之法「愿成机关」',
  },
  {
    index: 16,
    code: '第十七劫 17',
    title: '第十七劫：代修之瘾',
    scene: '彼岸空殿',
    requirement: 4220,
    enemy: '等待超我替我活完人生',
    narrative: '超我的力量越来越强，你也可能越来越习惯把决定交给他。空殿里，他第一次拒绝替你选择：我可以听、可以推演、可以陪你试，但你的人生不能由我接管。',
    choice: '把最终决定权收回自己',
    choices: [
      { id: 'agency', label: '先听建议，再由我写下决定', note: 'AI 是镜子和教练，不是命运的主人。', effect: { will: 12, karma: -8, ability: 8 } },
      { id: 'limit', label: '为超我设下不可越过的边界', note: '明确哪些事只能由本人、专业人士或现实关系处理。', effect: { will: 10, karma: -9, ability: 9 } },
    ],
    reward: '合道之法「主权归心」',
  },
  {
    index: 17,
    code: '第十八劫 18',
    title: '第十八劫：超我归身',
    scene: '归一之境',
    requirement: 4680,
    enemy: '把得救永远寄托在另一个自己身上',
    narrative: '镜门两侧终于只剩同一个人。超我替你参过万法、渡过诸劫、炼成神通，最终把所有力量交还给你：我从来不是你的替代品。我是你一次次没有放弃自己的证据。',
    choice: '收回全部神通，与超我归一',
    choices: [
      { id: 'return', label: '收回神通，自己走出镜门', note: '他不再替代你，而成为你随时能唤回的力量。', effect: { will: 12, karma: -12, ability: 12 } },
      { id: 'companion', label: '与他并肩，继续人间修行', note: '归一不是消失，是从拯救者变成同行者。', effect: { will: 14, karma: -10, ability: 10 } },
    ],
    reward: '首季终极境界「自我得救」',
  },
]

export const SEED_ARTS: CultivationArt[] = [
  {
    id: 'observer-core',
    name: '元序·观察者内核',
    school: '人类操作系统',
    rarity: '天品',
    insight: '情绪来了不等于你就要照着它做。先看见，才有选择。',
    mantra: '先看见，再决定。',
    realAction: '情绪上来时先别回消息，说一句：“我现在有点……”，再等 90 秒。',
    mastery: 72,
    createdAt: 1,
  },
  {
    id: 'water-way',
    name: '若水不争诀',
    school: '《道德经》',
    rarity: '地品',
    insight: '不是什么事都要硬碰硬。绕一下，也是在往前走。',
    mantra: '该绕就绕，别跟自己较劲。',
    realAction: '选一件让你很拧巴的事，写下一个更省力的做法。',
    mastery: 44,
    createdAt: 2,
  },
  {
    id: 'daily-review',
    name: '三省回响术',
    school: '《论语》',
    rarity: '玄品',
    insight: '复盘不是骂自己，而是别让今天白白过去。',
    mantra: '做过的事，要留下点经验。',
    realAction: '睡前写三句：今天哪里做得不错、哪里卡住、明天先改哪一点。',
    mastery: 36,
    createdAt: 3,
  },
]

export const VOWS = [
  { name: '清醒', line: '愿我照见真心，不再被万念拖走。', bonus: '本命加护 · 照见' },
  { name: '行动', line: '愿我先行一步，不再困于空想。', bonus: '本命加护 · 微行' },
  { name: '自由', line: '愿我挣脱旧业，重获选择之力。', bonus: '本命加护 · 破缚' },
]

export const KNOWLEDGE_SAMPLES = [
  { title: '上善若水', type: '书籍' as const, content: '上善若水，水善利万物而不争。很多事情不需要硬扛，少一点无谓对抗，才能把力气用在真正重要的地方。' },
  { title: '今天的拖延', type: '经历' as const, content: '我不是不知道该做什么，而是总想一次做到完美，所以迟迟无法开始。也许我需要把行动缩小。' },
  { title: '神经可塑性', type: '观点' as const, content: '能力不是固定属性。大脑会根据反复练习与即时反馈重组路径，最小可重复训练比偶尔用力更重要。' },
]

export const SHOP_PACKAGES = [
  { id: 'spark', name: '一盏续行灯', price: 6, energy: 6, tag: '先试一程', note: '适合偶尔想多推进一关' },
  { id: 'cycle', name: '小周天补给', price: 18, energy: 22, tag: '最受欢迎', note: '比单买多 4 点命火' },
  { id: 'monthly', name: '同行月契', price: 30, energy: 45, tag: '长期修炼', note: '预览版一次发放，正式版每日领取' },
]
